FROM python:3.12-slim
ENV PYTHONUNBUFFERED 1
RUN apt-get update -qq && apt-get install -y nodejs git npm libpq-dev
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
